# Site settings
name: ASAF
title: ASAF
subtitle: >
  After School Activity Finder
email: kristianb21@gmail.com
description: > # this means to ignore newlines until "url:"
  After School Activity Finder (ASAF). A single page application to assist with searching for activities for students to do after school.
url: "" # the base hostname & protocol for your site
baseurl: ""
permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      weight: 0
      subtitle: ""
      refs: []

# Include:  Add the following to all pages. permalink: "/example" name of html
# file without the ".html" should go where example is.
include: ['_pages']

# Exclude files or directories from being generated to the _site folder.
exclude: [vendor,"less", "Rakefile", "Gemfile", "Gemfile.lock", "doc",
"gulpfile.js","package.json", "node_modules", "README.md", "README-DEVs.md", "README-ADDING-CONTENT.md"]